apiVersion: v1
kind: Service
metadata:
  name: redis-ext
  namespace: ot-operators
spec:
  type: LoadBalancer
  selector:
    app: redis-replication
    redis-role: master
  ports:
    - port: 6379
      targetPort: 6379
