apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
data:
  grafana.ini: |
    [server]
    protocol = http
    http_addr =
    http_port = 3000
    root_url = https://rubinity.stackit.gg/grafana
    serve_from_sub_path = true

    [auth.anonymous]
    enabled = true
    org_role = Viewer

    [users]
    default_theme = light

    [analytics]
    reporting_enabled = false
    check_for_updates = false

    [log]
    mode = console
    level = info

    [paths]
    data = /var/lib/grafana
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning
  datasource.yaml: |
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      url: https://rubinity.stackit.gg/prometheus
      isDefault: true
      editable: false
    - name: Loki
      type: loki
      access: proxy
      url: http://loki.loki.svc.cluster.local:3100
      isDefault: false
      editable: false
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      securityContext:
        fsGroup: 472
      serviceAccountName: goapi-sa
      containers:
      - name: grafana-cont
        image: grafana/grafana:latest
        env:
          - name: GF_SECURITY_ADMIN_USER
            valueFrom:
              secretKeyRef:
                  name: grafana-admin
                  key: admin-user
          - name: GF_SECURITY_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                  name: grafana-admin
                  key: admin-password
        volumeMounts:
          - name: grafana-config
            mountPath: /etc/grafana/grafana.ini
            subPath: grafana.ini
          - name: grafana-config
            mountPath: /etc/grafana/provisioning/datasources/datasource.yaml
            subPath: datasource.yaml
          - name: grafana-storage
            mountPath: /var/lib/grafana
        ports:
        - containerPort: 3000
      volumes:
        - name: grafana-config
          configMap:
            name: grafana-config
        - name: grafana-storage
          persistentVolumeClaim:
            claimName: grafana-pvc


       
      
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-svc
  labels:
    app: grafana
spec:
  type: ClusterIP
  ports:
  - name: grafana
    protocol: TCP
    port: 3000
    targetPort: 3000
  selector:
    app: grafana
 