apiVersion: v1
kind: Service
metadata:
  name: frontest
  labels:
    app: simple-web
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  selector:
    app: simple-web

# spec:
#   selector:
#     app.kubernetes.io/name: MyApp
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 9376
