apiVersion: v1
kind: Pod
metadata:
  name: debug-pod
  namespace: olm
spec:
  restartPolicy: Never
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
  containers:
    - name: debug
      image: bitnami/kubectl:latest
      command: ["sleep", "3600"] # keeps pod alive for testing
      securityContext:
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        capabilities:
          drop:
            - ALL
        seccompProfile:
          type: RuntimeDefault
