apiVersion: v1
kind: Service
metadata:
  name: redis-svc
  labels:
    app: redis-ui
spec:
  type: ClusterIP
  ports:
  - name: redis-ui
    protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: redis-ui
